name: Aristotelis Georgoulis | Junior Software Engineer
description: Junior Software Engineer passionate about mobile, web and machine learning
meta_description: "Aristotelis Georgoulis, Junior Software Engineer, mobile development, web development and machine learning"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://4ris.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Aristotelis Georgoulis'
authorTwitter:  '@ArisGeorgoulis'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
